[package]
name = "spectra-demoscene-desktop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spectra-demoscene = { version = "0.1", path = "../spectra-demoscene" }
